import {AppProvider} from "@/components/AppContext";
import Header from "@/components/layout/header";
import { Roboto } from 'next/font/google'
import './globals.css'
import {Toaster} from "react-hot-toast";
import 'aos/dist/aos.css'; 
import { FaFacebook, FaInstagram, FaTiktok, FaYoutube } from 'react-icons/fa';
import Link from "next/link";


const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'] })

export const metadata = {
  title: 'Amifa Broasted Chicken',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={roboto.className}>
        <main className="max-w-4xl mx-auto p-4 overflow-y-hidden">
          <AppProvider>
            <Toaster />
            <Header className='mb-20 mr-5' />
            {children}
          </AppProvider>
        </main>
      </body>
    </html>
  )
}
